spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.138.158.118:5432/wn_mall
    username: pg1
    password: 123456
  redis:
    host: 43.138.158.118
    port: 6379
  rabbitmq:
    host: 43.138.158.118
    username: admin
    password: 123456
    port: 5672
    virtual-host: /
#  mail:
#    host: smtp.qq.com #SMTP服务器地址
#    username: 1048321255@qq.com #登陆账号
#    password: yepzkejtozjlbfee #登陆密码（或授权码）
mybatis-plus:
  global-config:
    db-config:
      table-prefix: mall_
      id-type: auto
  #mapper-locations: mappers.MenuMapper.xml
  #type-aliases-package: com.woniuxy.mall.mapper
logging:
  level:
    com.woniuxy.mall:
      mapper: debug
      web: debug
      filter: debug
      portal: debug

minio:
  endpoint: http://43.138.158.118:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: goods
JWT:
  secretKey: 123456

alipay:
  app_id: 2016092100562103
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCMLz6dlJJlP0ZHhPTCXKP5K2cixOYYLtQx6L1AJea/C6Fg+K+SaMNbGEcDa4WMuQM/9vtxr2Nr5QP6phTp2cU55ZtRijqqa7Y46A1LMjvklRmCXe/qllRtg5SKrtczimETEOMhc/802U3Fbg7wBSxdbO8w+EgTKJYcb/lZfMeRlZmSnE+3jQ1ZjmhC6rKm5xOHTuLkw9LlSmGpHbjonx7c/EzDxs3sMnDg1WvaMwWsxnHDTlw3gf3Uy1xf78CRUz5Li/GYVOxj3PeHzoteHAEyF5EHaVTWu1798dBMlffAD/wkXiYuR4tqufz1X05VNXDPhiEXTNo/qV7fCUDNWu/hAgMBAAECggEAUAzqhLHCp25qg4y4+ARO3oqaapBllImpQpbU+zypd478qJNaLxED/ZDvfFR5/tHnuS8ghtrQu1wb2ZXde2yP42/qMbXtqkO32ucoMDiPWwiJeJiL2DngHGl2+Xq+CQCMTobmLMRAh71PW95tSUKrAu6h6CTfg5E5pyOKED/g9pDKWT04DlDJ05yZUPFya08ttx/LjoEWTpI3m5FYiW5eRoWoYbbNpHh1NCcztbmn0+dy2JvvFTRGpl+8fhzYQIxtWTzghu0/V+KxpX6XtmW1cFFTKDd6sF6fppgw0ZBusq4aYXroXBjBCReu07ogNjrhPAKsf55z+5fJ72R3nTCMwQKBgQDnf4u39aKqfwcZ4hCrZaaH3G3Hmt0wxJYZnK2FmUGUa3QJ14SFzheNWhMkO13+qgCJUYbEqGW5I6whw1d4ZcxeF06yqaRtSXlYajjOYwEut2tpO9zMpzwlWJ5QkqSEJ5vFbPQcsVcnaHwFddixFsTBsV6vmLWYB95yuLSQ4/PnTwKBgQCbBY0G4NQ4y5l+4X1Nbv2cXrhfmJ4JOwXjQv3oe6URQCTjwwCd9SErrRcoctoUKU3L/Mmeck1wZf8kFHyMQ8rbkYdiliks30XlU1KOUlpUroE6Vgm4nhXvg3P0VOnl1qSAKMRDxrMefxApxDK/78fBBSxPcLm11hWHTG4IAaTpzwKBgBoPv9j77E4pctE1JA9HqFHPPQSlqJUe7I8Bln9d24Yr+qpI+wBdTUV6iIEhtdk/pkPPS87D7n/DRlOevDAvtaw6D4AJnRs4lFKh0rdZaf6qY4s7VAYuJZVGvrvvZloCY4T8WRcJ1/f1yVCMDdMR7yCnKTO3i2oMKLzdkmZlY0X9AoGATK3tOSbCsqk67sDYuxGYjt1nc5nJKiWw3t4HPBTU7Hh/Bs4xIvDajIEcwFw3NNvNaIZMsHw3g85f6tfbV4I8+Gi+v+wox9JU/388ibuAhPygXVuriU9g6E1scMIDxDVsvxvrIN9LQF13gEFVHQ2dEAPgDBdlNOWFVpxenMU7bo8CgYEAykc27kmYWs3aGPzCv6KxCRrhIpuWbyuKYbgNXU2Mz/kH/eCXRqG8/DKRhYsVYGoJPFkWsS1LTb9cPKlCK94bO7Ge39+nuvkbuUSeRTz5j0GlqaTefIz4TM1x7L+3C57L5FIa8rUP0Nwf2QquGISXktszqTPbxo4qJ3z95+Y6vWQ=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgWAE4YUhH75N3fsmDZewYM4CPOJ6ntAVt/ujEBIfbq3lblM83VZivWrcjBCU+m6Ps15I5NLzRSNhJWMf1LevWxGUFoYFpbnNY8n99VW2yFioMmQkZ/jJ+xOpBvZaCioP6/N+MaNPystto/8B5fOlxkwd8i3fj9cHSNVFk6fTT7GYTbeEwjrSlhNxJvnpajVkugB52840vP0zBSPeBE/ip9102gWpCiYTkaFpf80WbHtj140kcAMzKzLlLHvmLc2hYdCcGyCVcca9qELSdOOPXuwe1HK+MYj1BMNZM0VljeTQQWZAXbg8sMRPLR1UiuXq0yFMMsnAQzqttuWppl+zXwIDAQAB
  notify_url: http://localhost:8080/alipay/notify
  return_url: http://localhost:8080/alipay/return
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do
