spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://43.138.158.118:5432/wn_mall
    username: pg1
    password: 123456
  redis:
    host: 43.138.158.118
    port: 6379
  rabbitmq:
    host: 43.138.158.118
    username: admin
    password: 123456
    port: 5672
    virtual-host: /
#  mail:
#    host: smtp.qq.com #SMTP服务器地址
#    username: 1048321255@qq.com #登陆账号
#    password: yepzkejtozjlbfee #登陆密码（或授权码）
mybatis-plus:
  global-config:
    db-config:
      table-prefix: mall_
      id-type: auto
  #mapper-locations: mappers.MenuMapper.xml
  #type-aliases-package: com.woniuxy.mall.mapper
logging:
  level:
    com.woniuxy.mall:
      mapper: debug
      web: debug
      filter: debug
      portal: debug

minio:
  endpoint: http://43.138.158.118:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: goods
JWT:
  secretKey: 123456

