spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wn_mall
    username: postgres
    password: 123456
  redis:
    host: 192.168.11.191
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      table-prefix: mall_
      id-type: auto
  #mapper-locations: mappers.MenuMapper.xml
  #type-aliases-package: com.woniuxy.mall.mapper
logging:
  level:
    com.woniuxy.mall:
      mapper: debug
      web: debug
      filter: debug

minio:
  endpoint: http://192.168.11.191:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: goods
JWT:
  secretKey: 123456

